name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  discord-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send push message to Discord
        uses: Ilshidur/action-discord@v1
        with:
          args: |
            [${{ github.repository }}] Push by ${{ github.actor }} to `${{ github.ref_name }}`
            Latest commit: ${{ github.event.head_commit.message }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
