# This file will push GitHub notifications to a Discord bot

name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  discord-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send push message to Discord
        uses: Ilshidur/action-discord@master
        with:
          args: |
            **[${{ github.repository }}] New Push Detected**
            **Author:** ${{ github.actor }}
            **Branch:** `${{ github.ref_name }}`
            **Commit Message:**  
            > ${{ github.event.head_commit.message }}

            [View Commit](${{ github.event.head_commit.url }})
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
